/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signup
         * @description 아이디·비번 + 온보딩으로 계정 생성 후 JWT 발급. 중복 아이디는 409.
         */
        post: operations["signup_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description 아이디·비번 검증 후 JWT 발급. 실패 시 401(아이디 존재 여부 노출 안 함).
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/profile/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_auth_profile__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Content */
        get: operations["list_content_content_get"];
        put?: never;
        /**
         * Upload Content
         * @description HIVE-33: 사용자 글 업로드 → 태깅·임베딩·적재·Auto-HKG 편입.
         *
         *     올린 글이 기존 노드에 편입되거나 Auto-HKG가 새 하위/최상위 노드를 생성한다.
         */
        post: operations["upload_content_content_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content/{content_id}/synthesis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Synthesis
         * @description 재가공본(synthesis) 조회 — '읽기' 시 노출. 캐시 우선(ensure_synthesis):
         *     DB에 있으면 그대로 반환(Haiku 호출 없음), 없으면 1회 생성·저장. 키 없으면 null(graceful).
         */
        get: operations["get_synthesis_content__content_id__synthesis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommend/user-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User State
         * @description 유저 상태를 자연어 텍스트로 반환한다.
         */
        get: operations["get_user_state_recommend_user_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommend/mastery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Mastery
         * @description 노드별 mastery(0~1)를 반환한다.
         */
        get: operations["get_mastery_recommend_mastery_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recommend */
        get: operations["recommend_recommend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Read History
         * @description 유저가 읽은 콘텐츠를 읽은 순(오래된→최근)으로 반환한다 (HIVE-65 학습경로 '완료' 구간).
         *
         *     같은 글을 여러 번 읽었으면 가장 최근 읽음 시각으로 합쳐 한 번만 나온다.
         */
        get: operations["list_read_history_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark Read */
        patch: operations["mark_read_progress_patch"];
        trace?: never;
    };
    "/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Graph
         * @description 현재 지식그래프(topic/content 노드 + belongs_to/similar_to/precedes 엣지).
         *
         *     light=True면 가장 비싼 similar_to(콘텐츠 kNN)를 건너뛴다 — 주제 노드만 필요한
         *     화면이 26초짜리 유사도 계산을 기다리지 않도록(HIVE-65 주제별 숙련도용).
         */
        get: operations["get_graph_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Feedback
         * @description 유저의 모든 피드백을 {content_id: feedback}로 반환한다 (프론트 현재 상태 표시용).
         */
        get: operations["list_feedback_feedback_get"];
        /**
         * Set Feedback
         * @description 피드백을 저장하거나 갱신한다 (upsert).
         */
        put: operations["set_feedback_feedback_put"];
        post?: never;
        /**
         * Clear Feedback
         * @description 피드백을 제거한다 (토글 해제 → 추천 반영 복구).
         */
        delete: operations["clear_feedback_feedback_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthResponse
         * @description 가입/로그인 성공 시 JWT + 프로필 요약. 클라이언트(BFF)는 토큰을 httpOnly 쿠키로 저장.
         */
        AuthResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** User Id */
            user_id: number;
            /** Display Name */
            display_name: string;
            /** Persona */
            persona: string;
            /** Current Level */
            current_level: string;
        };
        /** ContentItem */
        ContentItem: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Url */
            url?: string | null;
            /** Source */
            source: string;
            /** Author Name */
            author_name?: string | null;
            /** Language */
            language?: string | null;
            /** Difficulty */
            difficulty?: string | null;
            /** Quality Score */
            quality_score?: number | null;
            /** Content Type */
            content_type?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: unknown[];
            /** Engagement Likes */
            engagement_likes?: number | null;
            /** Engagement Comments */
            engagement_comments?: number | null;
            /** Published At */
            published_at?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Summary */
            summary?: string | null;
        };
        /** ContentListResponse */
        ContentListResponse: {
            /** Items */
            items: components["schemas"]["ContentItem"][];
            /** Total */
            total: number;
        };
        /** ContentUpload */
        ContentUpload: {
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Url */
            url?: string | null;
        };
        /** FeedbackCreate */
        FeedbackCreate: {
            /** Content Id */
            content_id: number;
            /** Feedback */
            feedback: string;
        };
        /** FeedbackDelete */
        FeedbackDelete: {
            /** Content Id */
            content_id: number;
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            /** Status */
            status: string;
            /** Feedback */
            feedback?: string | null;
        };
        /** GraphEdge */
        GraphEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Rel */
            rel: string;
            /** Weight */
            weight: number;
        };
        /** GraphNode */
        GraphNode: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /**
             * Auto
             * @default false
             */
            auto: boolean;
        };
        /** GraphResponse */
        GraphResponse: {
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
            /** Stats */
            stats: Record<string, never>;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** MasteryResponse */
        MasteryResponse: {
            /** User Id */
            user_id: number;
            /** Mastery */
            mastery: {
                [key: string]: number;
            };
        };
        /** ProfileResponse */
        ProfileResponse: {
            /** User Id */
            user_id: number;
            /** Display Name */
            display_name: string;
            /** Persona */
            persona: string;
            /** Current Level */
            current_level: string;
        };
        /** ProgressResponse */
        ProgressResponse: {
            /** Status */
            status: string;
            /**
             * Read At
             * Format: date-time
             */
            read_at: string;
            /**
             * Leveled Up
             * @default false
             */
            leveled_up: boolean;
            /** New Level */
            new_level?: string | null;
            /** Influence Score */
            influence_score?: number | null;
        };
        /** ProgressUpdate */
        ProgressUpdate: {
            /** Content Id */
            content_id: number;
        };
        /** ReadHistoryItem */
        ReadHistoryItem: {
            /** Content Id */
            content_id: number;
            /** Title */
            title: string;
            /** Url */
            url?: string | null;
            /** Difficulty */
            difficulty?: string | null;
            /** Content Type */
            content_type?: string | null;
            /** Topic */
            topic?: string | null;
            /**
             * Read At
             * Format: date-time
             */
            read_at: string;
        };
        /** ReadHistoryResponse */
        ReadHistoryResponse: {
            /** User Id */
            user_id: number;
            /** Items */
            items: components["schemas"]["ReadHistoryItem"][];
        };
        /** RecommendResponse */
        RecommendResponse: {
            /** Recommendations */
            recommendations: components["schemas"]["Recommendation"][];
        };
        /** Recommendation */
        Recommendation: {
            /** Content Id */
            content_id: number;
            /** Title */
            title: string;
            /** Score */
            score: number;
            /** Reason */
            reason?: string | null;
            /** Url */
            url?: string | null;
            /** Difficulty */
            difficulty?: string | null;
            /** Content Type */
            content_type?: string | null;
            /** Summary */
            summary?: string | null;
            /** Topic */
            topic?: string | null;
        };
        /**
         * SignupRequest
         * @description 회원가입 = 기존 프로필(display_name·persona·온보딩) + 로그인 자격(아이디·비번).
         */
        SignupRequest: {
            /** Display Name */
            display_name: string;
            /**
             * Persona
             * @default 개발자
             */
            persona: string;
            /** Onboarding Answers */
            onboarding_answers?: {
                [key: string]: number;
            };
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** StatsResponse */
        StatsResponse: {
            /** User Id */
            user_id: number;
            /** Influence Score */
            influence_score: number;
            /** Streak */
            streak: number;
            /** Heatmap */
            heatmap: {
                [key: string]: number;
            };
        };
        /** SynthesisResponse */
        SynthesisResponse: {
            /** Content Id */
            content_id: number;
            /** Content Type */
            content_type?: string | null;
            /** Synthesis */
            synthesis?: Record<string, never> | null;
        };
        /** UploadResult */
        UploadResult: {
            /** Content Id */
            content_id: number;
            /** Title */
            title: string;
            /** Action */
            action: string;
            /** Node Id */
            node_id?: number | null;
            /** Node Name */
            node_name?: string | null;
            /** Is New Node */
            is_new_node: boolean;
            /** Difficulty */
            difficulty?: string | null;
            /** Content Type */
            content_type?: string | null;
        };
        /** UserStateResponse */
        UserStateResponse: {
            /** User Id */
            user_id: number;
            /** User State */
            user_state: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    signup_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_auth_profile__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_content_content_get: {
        parameters: {
            query?: {
                source?: string | null;
                node_id?: number | null;
                difficulty?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_content_content_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContentUpload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_synthesis_content__content_id__synthesis_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                content_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SynthesisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_state_recommend_user_state_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mastery_recommend_mastery_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MasteryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_recommend_get: {
        parameters: {
            query?: {
                top_n?: number;
            };
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_read_history_progress_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_read_progress_patch: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgressUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_graph_get: {
        parameters: {
            query?: {
                light?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_feedback_feedback_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_feedback_feedback_put: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_feedback_feedback_delete: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackDelete"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_stats_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}

// ─────────────────────────────────────────────────────────────────────────────
// HIVE-64 편의 타입 alias
// 백엔드 Pydantic ContentItem == 프런트 ContentResponse.
// page.tsx 에서 components["schemas"]["ContentResponse"]로 임포트 가능하도록
// top-level 타입 alias로 노출한다.
// ─────────────────────────────────────────────────────────────────────────────

/** /content 엔드포인트가 반환하는 단일 콘텐츠 항목 (ContentItem 의 alias). */
export type ContentResponse = components["schemas"]["ContentItem"];

/** /content 엔드포인트 목록 응답 전체 (ContentListResponse 의 alias). */
export type ContentListPayload = components["schemas"]["ContentListResponse"];
